# Generated by Django 5.2.11 on 2026-02-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(default='best_classifier', max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('input_obj', models.JSONField()),
                ('pred_obj', models.JSONField()),
                ('latency_ms', models.IntegerField()),
            ],
        ),
    ]
